version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore(ci)"
    directory: "/"
    labels:
      - "dependencies"
      - "github_actions"
      - "merge:queue"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore(docs)"
    directory: "/docs/"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    versioning-strategy: "increase"
  - package-ecosystem: "pip"
    commit-message:
      prefix: "chore(deps)"
    directory: "/"
    labels:
      - "dependencies"
      - "python"
      - "merge:queue"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
