queue_rules:
  - name: default
    allow_inplace_checks: false
    merge_method: rebase
    update_method: rebase
    merge_conditions:
      - check-success=Build the static site
      - check-success=Build the rolling release
      - check-success=Pre-commit (include linter)
      - check-success=All tests for minimal dependancies passed (or skipped)
      - check-success=All tests for stable dependancies passed (or skipped)

pull_request_rules:
  - name: Queue PRs
    conditions:
      - label=merge:queue
    actions:
      queue:
        allow_merging_configuration_change: true
  - name: Delete head branch
    conditions:
      - merged
    actions:
      delete_head_branch:
