nodeLinker: "node-modules"

packageExtensions:
  "vuepress@^2.0.0":
    peerDependencies:
      "vue": "^3.0.0"
      "@vuepress/client": "next"
  "@vueuse/core@^10.0.0":
    peerDependencies:
      "vue": "^3.0.0"
  "@vueuse/shared@^10.0.0":
    peerDependencies:
      "vue": "^3.0.0"
