name: Create new branches and PRs on assigned issues

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  issues:
    types: [assigned]
  pull_request:
    types: [closed]

jobs:
  create_branch_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: robvanderleek/create-issue-branch@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
