name: Fix yarn lockfile after dependabot

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.client_payload.pull_request.head.ref }}

on:
  repository_dispatch:
    types: [update-lockfile]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - run: rm docs/yarn.lock
      - uses: actions/download-artifact@v3.0.2
        with:
          name: yarn-lockfile--${{ github.event.client_payload.pull_request.head.sha }}
          path: docs/yarn.lock
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: GitHub
          author_email: noreply@github.com
          commit: --amend
          message: "${{ github.event.client_payload.pull_request.title }}"
      - run: gh pr edit ${{ github.event.client_payload.pull_request.number }} --add-label "merge:queue"
