name: Fix yarn lockfile after dependabot

on:
  workflow_run:
    workflows: [Prepare yarn lockfile after dependabot]
    types: [completed]

jobs:
  commit-lockfile:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: rm docs/yarn.lock
      - uses: dawidd6/action-download-artifact@v2.26.0
        with:
          name: yarn-lockfile--${{ github.event.workflow_run.head_sha }}
          path: docs/yarn.lock
          run_id: ${{ github.event.workflow_run.id }}
          workflow: prepare-yarn-lockfile.yml
      - uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: GitHub
          author_email: noreply@github.com
          commit: --amend
          message: "${{ github.event.workflow_run.head_commit.message }}"
      - run: gh pr edit ${{ github.event.workflow_run.pull_requests[0].number }} --add-label "merge:queue"
