name: Dependabot on pre-commit hooks

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize, unlocked]
    paths:
      - ".github/workflows/pre-commit.yml"
      - ".pre-commit-config.yaml"
  schedule:
    - cron: 37 5 * * *
  workflow_dispatch:

jobs:
  update:
    if: ${{ ! endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4.5.0
        with:
          cache: pip
          cache-dependency-path: .github/requirements-ci.lock
          check-latest: true
          python-version: 3.11
      - run: python -m pip config --user set install.use-pep517 true
      - run: python -m pip install -r .github/requirements-ci.lock
      - run: pre-commit autoupdate
      - id: cache-pre-commit
        uses: actions/cache@v3.3.1
        with:
          key: ${{ hashFiles('.pre-commit-config.yaml') }}
          path: ~/.cache/pre-commit
      - if: ${{ ! steps.cache-pre-commit.outputs.cache-hit }}
        run: pre-commit install-hooks
      - uses: peter-evans/create-pull-request@v5.0.0
        with:
          author: "GitHub <noreply@github.com>"
          base: ${{ github.head_ref || github.ref_name }}
          branch: dependabot/pre-commit/${{ github.head_ref || github.ref_name }}
          committer: "GitHub <noreply@github.com>"
          commit-message: "chore(dev): bump pre-commit hooks"
          labels: |
            dependencies
            merge:queue
            pre-commit
          title: "chore(dev): bump pre-commit hooks"
