name: Trigger workflow event for dependabot PRs

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref }}

on:
  pull_request:
    branches: [main]
    types: [labeled, opened, reopened, synchronize, unlocked]

jobs:
  trigger-amend-prs:
    if: github.actor == 'dependabot[bot]' && !contains( github.event.pull_request.labels.*.name, 'merge:queue')
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
